name: Workflow commands
on: [push]

jobs: 
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"  
      - name: Setting an error message with params
        run: echo "::error tittle=Error title, file=app.js, line=2, endLine=2,col=5,endColumn=7::Missing Semicolor"
      - name: Setting an debug message with params
        run: echo "::debug tittle=Debug title, file=app.js, line=2, endLine=2,col=5,endColumn=7::Missing Semicolor"
      - name: Setting an warning message with params
        run: echo "::warning tittle=Warning title, file=app.js, line=2, endLine=2,col=5,endColumn=7::Missing Semicolor"
      - name: Setting an notice message with params
        run: echo "::notice tittle=Notice title, file=app.js, line=2, endLine=2,col=5,endColumn=7::Missing Semicolor"
      - name: Group of logs
        run: |
          echo "::group:: My group title"
          echo "Inside group"
          echo "::endgroup::"
      - name: Masking a value
        run: echo "::add-mask::Secret string"
      - name: Echo a secret
        run: echo "Secret string"